// ─── CATÁLOGO COMPLETO MAG SUPLEMENTOS ───────────────────────────────────────
// Fuente: mag-rep-oficial.com.ar
// Todos los precios en pesos argentinos (ARS)

const PRODUCTOS = [
  // ── PROTEÍNAS ──────────────────────────────────────────────────────────────
  {
    id: 1, nombre: 'W-Mass 1kg', categoria: 'Proteínas / Gainers',
    precio: 72000,
    descripcion: 'Whey protein + carbohidratos complejos para hipertrofia y volumen muscular.',
    paraQuien: 'Personas que quieren ganar masa muscular y peso. Ideal para hardgainers.',
    comoTomar: '1 scoop (40g) post-entreno con agua o leche. También se puede tomar antes de dormir.',
    sabores: ['Cookies & Cream', 'Vainilla'],
    presentacion: '1kg — aprox. 25 porciones',
    destacado: true,
  },
  {
    id: 17, nombre: 'MAX-80 Whey + Eggs', categoria: 'Proteínas',
    precio: 86000,
    descripcion: 'Proteína de suero y huevo al 80% de concentración. 32g de proteína por porción para máxima hipertrofia.',
    paraQuien: 'Atletas que buscan una fuente proteica doble (suero + huevo) para síntesis muscular superior.',
    comoTomar: '1 scoop post-entreno con agua o leche.',
    presentacion: '1kg — 25 porciones — 32g proteína/porción',
    sabores: [],
    nuevo: true,
  },
  {
    id: 18, nombre: 'Protein W80', categoria: 'Proteínas',
    precio: 94000,
    descripcion: 'Concentrado de proteína de suero de leche al 80%. Disolución instantánea. 7 sabores disponibles.',
    paraQuien: 'Cualquier persona que haga actividad física y quiera aumentar su ingesta proteica. El más vendido.',
    comoTomar: '1 scoop (27g) post-entreno. También entre comidas para completar proteína diaria.',
    sabores: ['Chocolate', 'Vainilla', 'Frutilla', 'Frutos Rojos', 'Dulce de Leche', 'Banana', 'Banana Split'],
    presentacion: '1kg — 37 porciones — 80% proteína',
    nuevo: true,
  },
  {
    id: 19, nombre: 'EGG PROT Ovoalbúmina', categoria: 'Proteínas',
    precio: 66000,
    descripcion: 'Proteína pura de huevo, libre de lactosa. Perfil completo de aminoácidos.',
    paraQuien: 'Personas con intolerancia a la lactosa o que prefieren evitar lácteos. También para quienes buscan diversificar fuentes proteicas.',
    comoTomar: '1 scoop post-entreno con agua o leche vegetal.',
    sabores: ['Chocolate'],
    presentacion: '1kg — 33 porciones — 25g proteína/porción — Sin lactosa',
  },
  {
    id: 20, nombre: 'Total Gainer 1.5kg', categoria: 'Gainers',
    precio: 66000,
    descripcion: 'Advanced Muscle & Mass Gainer. Carbohidratos complejos + proteína para subir de peso y volumen de forma efectiva.',
    paraQuien: 'Personas con metabolismo rápido que no logran subir de peso. Hardgainers y ectomorfos.',
    comoTomar: '1-2 scoops post-entreno o entre comidas.',
    presentacion: '1.5kg — 37 porciones — 12g proteína/porción',
    sabores: [],
  },
  {
    id: 42, nombre: 'Protein W80 Hidrolizada 1kg', categoria: 'Proteínas Premium',
    precio: 123000,
    descripcion: 'Proteína de suero hidrolizada de máxima absorción. Ideal para post-entreno inmediato.',
    paraQuien: 'Atletas avanzados y personas con digestión sensible. La hidrolización predigiere la proteína para absorción casi instantánea.',
    comoTomar: '1 scoop inmediatamente después del entreno, con agua fría.',
    sabores: ['Vainilla', 'Chocolate'],
    presentacion: '1kg — Alta absorción',
    nuevo: true,
  },
  {
    id: 47, nombre: 'Pure Plant Vegetal Premium 1kg', categoria: 'Proteínas Veganas',
    precio: 51000,
    descripcion: 'Proteína vegetal premium de Poroto Mungo, Arroz y Arveja. Perfil completo de aminoácidos, sin lactosa, sin gluten.',
    paraQuien: 'Veganos, vegetarianos o cualquier persona que quiera evitar proteínas de origen animal. 100% vegetal.',
    comoTomar: '1 scoop post-entreno o entre comidas.',
    presentacion: '1kg — Vegana — Sin lactosa — Sin gluten',
    nuevo: true,
    sabores: [],
  },
  {
    id: 34, nombre: 'Flex-V Vegetarian Protein', categoria: 'Proteínas Veganas',
    precio: 32000,
    descripcion: 'Proteína flexitariana premium. 30g de proteína por porción de fuentes vegetales de alta calidad.',
    paraQuien: 'Flexitarianos y personas que reducen el consumo de proteína animal sin eliminarlo completamente.',
    comoTomar: '1 scoop post-entreno o entre comidas.',
    sabores: ['Vainilla'],
    presentacion: '400g — 13 porciones — 30g proteína/porción',
    nuevo: true,
  },

  // ── CREATINAS ──────────────────────────────────────────────────────────────
  {
    id: 2, nombre: 'High Creatine Power', categoria: 'Creatinas',
    precio: 33000,
    descripcion: 'Creatina monohidrato de pureza farmacéutica. Fuerza, explosividad y volumen celular garantizados.',
    paraQuien: 'Cualquier deportista. La creatina es el suplemento más estudiado del mundo. Sirve para gym, crossfit, fútbol, correr y cualquier actividad.',
    comoTomar: '3-5g por día disueltos en agua o jugo. Se puede tomar en cualquier momento del día. No requiere carga.',
    presentacion: '250g — 83 porciones — Sin sabor',
    sabores: ['Sin sabor'],
  },
  {
    id: 21, nombre: 'Crea Power 500g', categoria: 'Creatinas',
    precio: 38000,
    descripcion: 'Creatina monohidrato de alta pureza en presentación grande. Para ciclos prolongados.',
    paraQuien: 'Atletas que ya consumen creatina y quieren una presentación más económica por porción.',
    comoTomar: '3-5g por día con agua. Se puede combinar con jugo de fruta para mejor absorción.',
    presentacion: '500g — 83+ porciones — Sin sabor',
    sabores: ['Sin sabor'],
  },
  {
    id: 22, nombre: 'MAG Creatine 300g', categoria: 'Creatinas',
    precio: 29000,
    descripcion: 'Creatina monohidrato ultrafina. Explosividad máxima en cada sesión.',
    paraQuien: 'Atletas de fuerza y potencia. También para quienes quieren empezar a tomar creatina.',
    comoTomar: '3-5g por día con agua o jugo. Puede tomarse antes o después del entreno.',
    presentacion: '300g — 50 porciones — Sin sabor',
    sabores: ['Sin sabor'],
  },

  // ── PRE-ENTRENOS ───────────────────────────────────────────────────────────
  {
    id: 3, nombre: 'Pre-Workout MAG', categoria: 'Pre-Entrenos',
    precio: 36000,
    descripcion: 'Beta-alanina, arginina, citrulina y cafeína en la dosis justa. Energía y pump durante 60 minutos.',
    paraQuien: 'Deportistas que buscan más energía, concentración y rendimiento en el entreno.',
    comoTomar: '1 scoop (7.5g) en 300ml de agua fría, 20-30 minutos antes del entreno. No tomar de noche si sos sensible a la cafeína.',
    sabores: ['Pomelo'],
    presentacion: '300g — 40 porciones',
  },
  {
    id: 26, nombre: 'V12 Energy 650g', categoria: 'Pre-Entrenos / Energizantes',
    precio: 30000,
    descripcion: 'Bebida energizante con cafeína natural, taurina y vitaminas del grupo B. Activación total.',
    paraQuien: 'Deportistas y personas que necesitan energía extra para entrenar o para el día a día.',
    comoTomar: '1 scoop en agua fría antes de entrenar o cuando necesites energía.',
    sabores: ['Multifrutal'],
    presentacion: '650g — Estimulante natural',
    nuevo: true,
  },

  // ── AMINOÁCIDOS ────────────────────────────────────────────────────────────
  {
    id: 4, nombre: 'EAA MAG', categoria: 'Aminoácidos Esenciales',
    precio: 33000,
    descripcion: '9 aminoácidos esenciales para tomar intra-entreno. Reduce fatiga y acelera recuperación muscular.',
    paraQuien: 'Atletas que entrenan en ayunas o quieren maximizar la recuperación durante el entreno.',
    comoTomar: '1 scoop (7.5g) en agua durante el entreno. Se puede combinar con creatina.',
    sabores: ['Limonada'],
    presentacion: '300g — 40 porciones',
    nuevo: true,
  },
  {
    id: 23, nombre: 'BCAA 8:1:1', categoria: 'Aminoácidos',
    precio: 23000,
    descripcion: 'Ratio 8:1:1 de Leucina, Isoleucina y Valina. Máxima síntesis proteica y recuperación acelerada.',
    paraQuien: 'Deportistas que buscan preservar músculo en dieta o acelerar la recuperación post-entreno.',
    comoTomar: '1 scoop durante o después del entreno en agua.',
    sabores: ['Frutos Rojos'],
    presentacion: '250g — 40 porciones',
  },
  {
    id: 24, nombre: 'BCAA Premium 120 cáps', categoria: 'Aminoácidos',
    precio: 33000,
    descripcion: 'BCAAs en cápsula de liberación prolongada. Cómodo para llevar y tomar en cualquier momento.',
    paraQuien: 'Personas que prefieren cápsulas a los polvos. Ideal para viajes o trabajo.',
    comoTomar: '4 cápsulas antes o después del entreno. También se puede tomar entre comidas.',
    presentacion: '120 cápsulas — 60 días de uso',
    sabores: [],
  },
  {
    id: 25, nombre: 'L-Glutamine Max 120 cáps', categoria: 'Aminoácidos',
    precio: 17000,
    descripcion: 'L-Glutamina de alta concentración. Recuperación muscular, regeneración de tejidos y refuerzo inmune.',
    paraQuien: 'Atletas con entrenamientos intensos o frecuentes. También para personas con digestión sensible.',
    comoTomar: '2-4 cápsulas post-entreno. También se puede tomar antes de dormir.',
    presentacion: '120 cápsulas — 60 días',
    sabores: [],
  },
  {
    id: 27, nombre: 'Post Workout MAG', categoria: 'Recuperación',
    precio: 30000,
    descripcion: 'Fórmula post-entrenamiento con creatina, BCAAs e isomaltulose. Recuperación y recarga muscular real.',
    paraQuien: 'Atletas que buscan una fórmula todo-en-uno para el post-entreno.',
    comoTomar: '1 scoop inmediatamente después del entreno con agua.',
    sabores: ['Multifrutal'],
    presentacion: '300g — 40 porciones',
    nuevo: true,
  },

  // ── QUEMADORES / DEFINICIÓN ────────────────────────────────────────────────
  {
    id: 7, nombre: 'L-Carnitina MAG', categoria: 'Quemadores',
    precio: 18000,
    descripcion: 'Transporta grasa hacia las mitocondrias para usarla como energía. Ideal para deportes de resistencia y definición.',
    paraQuien: 'Personas que quieren quemar grasa, deportistas de endurance (running, ciclismo) y quienes hacen dieta de definición.',
    comoTomar: '2 cápsulas antes del entreno cardiovascular, con el estómago semi-vacío para mejor efecto.',
    presentacion: '100 cápsulas — 500mg — 50 días',
    sabores: [],
  },
  {
    id: 10, nombre: 'Fat Burner MAG', categoria: 'Quemadores',
    precio: 32000,
    descripcion: 'Guaraná, Garcinia Cambogia y té verde. Acelera el metabolismo y reduce el apetito.',
    paraQuien: 'Personas que quieren perder grasa y controlar el apetito. Funciona mejor combinado con dieta y ejercicio.',
    comoTomar: '2 cápsulas antes del desayuno y 2 antes del almuerzo. No tomar después de las 17hs.',
    presentacion: '60 cápsulas — 30 días',
    sabores: [],
  },
  {
    id: 28, nombre: 'Lipo Max 100 comp', categoria: 'Quemadores',
    precio: 44000,
    descripcion: 'Termogénico en comprimidos. Acelera el metabolismo y potencia la quema de grasa.',
    paraQuien: 'Personas en proceso de definición que buscan un termogénico potente en formato comprimido.',
    comoTomar: '2 comprimidos antes del desayuno. Empezar con 1 para evaluar tolerancia.',
    presentacion: '100 comprimidos — 50 días',
    sabores: [],
  },
  {
    id: 29, nombre: 'Lipolitic 120 comp', categoria: 'Quemadores',
    precio: 41000,
    descripcion: 'Fórmula lipolitica avanzada. Activa movilización de grasa y reduce retención de líquidos.',
    paraQuien: 'Personas que buscan quemar grasa y reducir retención de líquidos simultáneamente.',
    comoTomar: '2 comprimidos antes de las comidas principales.',
    presentacion: '120 comprimidos — 60 días — Drenante',
    sabores: [],
  },
  {
    id: 30, nombre: 'C.L.A.', categoria: 'Quemadores',
    precio: 36000,
    descripcion: 'Ácido Linoleico Conjugado. Preserva masa magra mientras reduce grasa corporal.',
    paraQuien: 'Personas en fase de definición que quieren quemar grasa sin perder músculo.',
    comoTomar: '3 softgels por día con las comidas.',
    presentacion: '150g — Softgels — Composición corporal',
    sabores: [],
  },
  {
    id: 45, nombre: 'Metabolix Advance 90 cáps', categoria: 'Quemadores',
    precio: 30000,
    descripcion: 'Fórmula termogénica avanzada para acelerar el metabolismo, quemar grasa y potenciar el rendimiento.',
    paraQuien: 'Atletas y personas que buscan un termogénico completo con efecto en rendimiento deportivo también.',
    comoTomar: 'Consultar disponibilidad — ingreso reciente.',
    presentacion: '90 cápsulas — 30 días',
    nuevo: true, ingresoReciente: true,
    sabores: [],
  },

  // ── ENERGÍA / PUMP ─────────────────────────────────────────────────────────
  {
    id: 6, nombre: 'V12 Drink Isotónico', categoria: 'Hidratación / Energía',
    precio: 15000,
    descripcion: 'Electrolitos, vitaminas del grupo B y carbohidratos de absorción rápida. Ideal intra-esfuerzo.',
    paraQuien: 'Deportistas de resistencia (running, ciclismo, fútbol, surf). Para reposición de sales y energía durante el esfuerzo.',
    comoTomar: '1 scoop en 500ml de agua durante el entreno o competencia.',
    sabores: ['Frutos Rojos', 'Lima-Limón'],
    presentacion: '650g',
  },
  {
    id: 31, nombre: 'BETA', categoria: 'Resistencia',
    precio: 15000,
    descripcion: 'Beta-Alanina pura en cápsulas. Reduce el ácido láctico y aumenta la resistencia muscular.',
    paraQuien: 'Atletas que hacen series largas o entrenamientos de alta intensidad y quieren retrasar la fatiga.',
    comoTomar: '2-4 cápsulas 30 minutos antes del entreno. Puede causar hormigueo leve (efecto normal).',
    presentacion: '100 cápsulas — 50 días',
    sabores: [],
  },
  {
    id: 32, nombre: 'Óxido Nítrico', categoria: 'Pump / Vasodilatación',
    precio: 19000,
    descripcion: 'L-Arginina Alpha Ketoglutarato para máximo pump y vasodilatación. Más sangre y nutrientes en el músculo activo.',
    paraQuien: 'Atletas de fuerza que buscan el efecto de pump máximo durante el entreno.',
    comoTomar: '2 cápsulas 30-45 minutos antes del entreno con el estómago vacío.',
    presentacion: '100 cápsulas — 50 días',
    sabores: [],
  },

  // ── BIENESTAR / SALUD ──────────────────────────────────────────────────────
  {
    id: 5, nombre: 'Tribulus Terrestris', categoria: 'Bienestar / Testosterona',
    precio: 68000,
    descripcion: '350mg por comprimido. Energía, libido y recuperación del tejido muscular.',
    paraQuien: 'Hombres mayores de 18 años que buscan apoyo hormonal natural, energía y recuperación.',
    comoTomar: '1-2 comprimidos por día con las comidas.',
    presentacion: '100 comprimidos — 100 días — Extracto puro',
    sabores: [],
  },
  {
    id: 8, nombre: 'Collagen Fit', categoria: 'Colágeno / Belleza',
    precio: 39000,
    descripcion: 'Colágeno hidrolizado con vitamina C, ácido hialurónico y resveratrol. Para piel, pelo y articulaciones.',
    paraQuien: 'Mujeres y hombres que quieren mejorar piel, cabello, uñas y cuidar sus articulaciones.',
    comoTomar: '1 scoop en agua tibia o jugo por día, preferentemente en ayunas.',
    sabores: ['Cítrico'],
    presentacion: '300g — 30 porciones',
    nuevo: true,
  },
  {
    id: 35, nombre: 'Collagen 90', categoria: 'Colágeno',
    precio: 33000,
    descripcion: 'Colágeno hidrolizado tipo I y III. Regenera cartílagos, mejora la piel y refuerza ligamentos y tendones.',
    paraQuien: 'Deportistas con dolores articulares, personas mayores de 30 años y quienes cuidan su piel.',
    comoTomar: '1 scoop por día con agua o jugo. Tratamiento de al menos 90 días para ver resultados.',
    presentacion: '400g — 90 días — Anti-aging',
    nuevo: true,
    sabores: [],
  },
  {
    id: 9, nombre: 'Ginseng Complex', categoria: 'Energía / Foco',
    precio: 66000,
    descripcion: 'Ginseng + Guaraná + Ginkgo Biloba. Foco, energía limpia y resistencia mental sin cafeína añadida.',
    paraQuien: 'Personas que necesitan concentración y energía mental: estudiantes, profesionales, deportistas.',
    comoTomar: '2 cápsulas por día con el desayuno.',
    presentacion: '120 cápsulas — 60 días — Sin cafeína añadida',
    sabores: [],
  },
  {
    id: 33, nombre: '+24 Vitaminas', categoria: 'Vitaminas / Inmunidad',
    precio: 40000,
    descripcion: 'Complejo multivitamínico con más de 24 nutrientes esenciales. Refuerza el sistema inmune y el bienestar general.',
    paraQuien: 'Cualquier persona que quiera asegurarse de cubrir todos los micronutrientes diarios.',
    comoTomar: '2 cápsulas por día con el desayuno.',
    presentacion: '120 cápsulas — 60 días',
    sabores: [],
  },
  {
    id: 50, nombre: 'Vitamina E 250mg', categoria: 'Vitaminas / Inmunidad',
    precio: 72000,
    descripcion: 'Vitamina E 250mg por cápsula. Potente antioxidante, protege las células del estrés oxidativo, apoya la salud cardiovascular.',
    paraQuien: 'Deportistas que necesitan antioxidantes, personas mayores de 30 años, personas que quieren proteger su salud celular.',
    comoTomar: '1 cápsula por día con el desayuno.',
    presentacion: '100 cápsulas — 100 días — 250mg',
    sabores: [],
  },
  {
    id: 51, nombre: 'Vitamina C', categoria: 'Vitaminas / Inmunidad',
    precio: 27000,
    descripcion: 'Vitamina C de alta concentración. Refuerza el sistema inmune, favorece la síntesis de colágeno y actúa como antioxidante.',
    paraQuien: 'Cualquier persona que quiera reforzar sus defensas, deportistas, personas propensas a resfriarse.',
    comoTomar: '1 cápsula por día con las comidas.',
    presentacion: '100 cápsulas — 100 días',
    sabores: [],
  },
  {
    id: 43, nombre: 'Bisglicinato de Magnesio 500mg', categoria: 'Minerales',
    precio: 41000,
    descripcion: 'Magnesio en su forma más biodisponible. Favorece la función muscular, nerviosa y el descanso nocturno.',
    paraQuien: 'Deportistas con calambres, personas con estrés o dificultad para dormir.',
    comoTomar: 'Consultar disponibilidad — ingreso reciente.',
    presentacion: '100 cápsulas — 500mg — 100 días',
    nuevo: true, ingresoReciente: true,
    sabores: [],
  },
  {
    id: 44, nombre: 'Cúrcuma Complex 250g', categoria: 'Antiinflamatorios Naturales',
    precio: 78000,
    descripcion: 'Extracto de cúrcuma + piperina para máxima absorción. Propiedades antiinflamatorias y antioxidantes naturales.',
    paraQuien: 'Personas con procesos inflamatorios, dolores articulares o que buscan antioxidantes naturales.',
    comoTomar: 'Consultar disponibilidad — ingreso reciente.',
    presentacion: '250g — Con piperina',
    nuevo: true, ingresoReciente: true,
    sabores: [],
  },
  {
    id: 46, nombre: 'GABA PLUS 100 cáps', categoria: 'Sueño / Recuperación',
    precio: 20000,
    descripcion: 'Fórmula natural con GABA, melatonina, valeriana y magnesio para sueño profundo y recuperación nocturna.',
    paraQuien: 'Personas con dificultad para dormir, atletas que quieren optimizar la recuperación nocturna.',
    comoTomar: 'Consultar disponibilidad — ingreso reciente.',
    presentacion: '100 cápsulas — Con GABA + Melatonina',
    nuevo: true, ingresoReciente: true,
    sabores: [],
  },
  {
    id: 49, nombre: 'Detox Pro 60 cáps', categoria: 'Detox',
    precio: 35000,
    descripcion: 'Fórmula detoxificante avanzada. Depura el organismo, favorece la función hepática y elimina toxinas.',
    paraQuien: 'Personas que quieren una limpieza del organismo o mejorar la función hepática.',
    comoTomar: 'Consultar disponibilidad — ingreso reciente.',
    presentacion: '60 cápsulas',
    nuevo: true, ingresoReciente: true,
    sabores: [],
  },

  // ── ACCESORIOS ─────────────────────────────────────────────────────────────
  {
    id: 37, nombre: 'Shaker MAG Pro', categoria: 'Accesorios',
    precio: 14000,
    descripcion: 'Shaker 500cc con compartimento inferior para suplementos y filtro anti-grumos. 6 colores.',
    paraQuien: 'Cualquier persona que mezcle suplementos en polvo.',
    comoTomar: 'N/A',
    sabores: ['Negro', 'Azul', 'Violeta', 'Rosa', 'Amarillo', 'Rojo'],
    presentacion: '500cc — 6 colores disponibles',
    sinStock: true,
  },
  {
    id: 36, nombre: 'Galón MAG Negro', categoria: 'Accesorios',
    precio: 15000,
    descripcion: 'Botellón deportivo 1600cc con logo MAG serigrafía. Para mantenerse hidratado todo el día.',
    presentacion: '1600cc — BPA free — Negro',
    sabores: [],
  },
  {
    id: 38, nombre: 'Galón MAG Azul', categoria: 'Accesorios',
    precio: 15000,
    descripcion: 'Botellón deportivo 1600cc con logo MAG serigrafía en blanco.',
    presentacion: '1600cc — BPA free — Azul',
    sabores: [],
  },
  {
    id: 39, nombre: 'Galón MAG Rojo', categoria: 'Accesorios',
    precio: 15000,
    descripcion: 'Botellón deportivo 1600cc con logo MAG.',
    presentacion: '1600cc — BPA free — Rojo',
    sabores: [],
  },
  {
    id: 40, nombre: 'Galón MAG Rosa', categoria: 'Accesorios',
    precio: 15000,
    descripcion: 'Botellón deportivo 1600cc con logo MAG. Diseño rosa.',
    presentacion: '1600cc — BPA free — Rosa',
    nuevo: true,
    sabores: [],
  },
];

// Índice para búsqueda rápida por nombre
function buscarProducto(texto) {
  const t = texto.toLowerCase();
  return PRODUCTOS.filter(p =>
    p.nombre.toLowerCase().includes(t) ||
    p.categoria.toLowerCase().includes(t) ||
    (p.descripcion && p.descripcion.toLowerCase().includes(t))
  );
}

// Generar texto del catálogo para el prompt de IA
function generarCatalogoParaIA() {
  return PRODUCTOS.map(p => {
    const precio = p.ingresoReciente ? 'consultar disponibilidad' : `$${p.precio.toLocaleString('es-AR')}`;
    const sabores = p.sabores && p.sabores.length > 0 ? ` | Sabores: ${p.sabores.join(', ')}` : '';
    return `• ${p.nombre} (${p.categoria}) — ${precio}${sabores} | ${p.presentacion || ''} | ${p.descripcion}`;
  }).join('\n');
}

module.exports = { PRODUCTOS, buscarProducto, generarCatalogoParaIA };
